.MODEL MEDIUM
.STACK 100H

.DATA
MYARRAY DW -45, 1000, -34, 1500, 20, 60
COUNT EQU 6 ; SIX ELEMENTS IN THE ARRAY
RESULT DW 0

.CODE
   MOV AX,@DATA
   MOV DS, AX
   MOV CX, COUNT
   LEA SI, MYARRAY ;LOAD EFFECTIVE ADDRESS OF ARRAY
   ;CALL FINDMIN
   ;TO DO
   
   MOV AH,BYTE PTR[SI]
LOOP1:CMP AL,BYTE PTR[SI]
     JNC LOOP2    ; IF NO CARRY MOVE TO NEXT LOOP
     MOV AL,BYTE PTR[SI];IF CARRY EXISTS NUMBER WILL MOVE TO AL

LOOP2:CMP AH,BYTE PTR[SI]
     JC LOOP3;
     MOV AH,BYTE PTR[SI]

LOOP3:INC SI      ;INCREMENT SI FOR NEXT VALUE IN THE ARRAY
     DEC CX       ;COUNTER DECREMENT
     CMP CX,00    ;CHECK WHEATHER ARRAY FINISHED
     JNZ LOOP1    ;ELSE JUMP TO LOOP1
     MOVE AH,4CH
     INT 21H
     
     Exit

END